# Generated by Django 5.0.6 on 2024-07-11 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shops", "0002_alter_magazaurunu_urun_resmi_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                ("delivery_address", models.TextField()),
                (
                    "paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("is_complete", models.BooleanField(default=False)),
                ("payment_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Customer Orders",
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "customer_order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="payment.customerorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shops.magazaurunu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShippingAdress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=264)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=264)),
                ("adress", models.TextField()),
                ("city", models.CharField(max_length=264)),
                ("zip", models.CharField(max_length=264)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ShippingAdresses",
            },
        ),
    ]
