# Generated by Django 5.0.6 on 2024-07-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magazaurunu",
            name="urun_resmi",
            field=models.ImageField(upload_to="urun_fotograflari2/"),
        ),
        migrations.AlterField(
            model_name="urunkategorisi",
            name="etiket",
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="urunkategorisi",
            name="yol_adi",
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
