# Generated by Django 5.0.6 on 2024-07-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_alter_magazaurunu_urun_resmi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="magazaurunu",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="magazaurunu",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
